config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :expenses
  end
  get 'budget', to: 'users#landing_page', as: 'budget'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "groups#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Group, user_id: user.id
    can :manage, Operation, author_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :group
  belongs_to :expense
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :groups, through: :categorizations, dependent: :destroy
  belongs_to :author, class_name: 'User'

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :expenses, through: :categorizations, dependent: :destroy
  belongs_to :user

  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user_id, message: ' already exist'

  def total_amount
    expenses.sum(:amount)
  end

  ICONS = {
    'fa-car' => 'Car',
    'fa-credit-card' => 'Credit Card',
    'fa-solid fa-gift fa-lg' => 'Gift'
  }.freeze
end

app/models/group_operation.rb
class GroupOperation < ApplicationRecord
  belongs_to :group
  belongs_to :operation

  validates :operation, :group, presence: true
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_operations, dependent: :destroy
  has_many :groups, through: :group_operations

  validates :name, presence: true
  validates :amount, presence: true, numericality: { allow_nil: false }

  def owned_by?(user)
    author_id == user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  has_many :expenses, dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[show edit update destroy]
  before_action :set_group, only: %i[index new create]
  before_action :authenticate_user!

  # GET /expenses or /expenses.json
  def index
    @expenses = @group.expenses.where(author_id: current_user.id).order('created_at Desc')

    @total_amount = 0
    # Loop through expenses and tally amounts
    @expenses.each do |expense|
      @total_amount += expense.amount
    end
  end

  # GET groups/group_id/expenses/new
  def new
    @expense = Expense.new(group_ids: [params[:group_id]])
  end

  # POST /expenses or /expenses.json
  def create
    puts 'Received expense parameters:'
    p params[:expense]

    @expense = Expense.new(expense_params)
    @expense.author_id = current_user.id

    @expense.name = @expense.name.capitalize

    if @expense.save
      redirect_to group_expenses_path(@group), notice: 'Transaction was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:expenses).where(user_id: current_user.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = current_user.groups.new(group_params)
    @group.name = @group.name.capitalize

    if @group.save
      redirect_to groups_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def splash_page; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_group, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!

  # GET /groups or /groups.json
  def landing_page; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, :html => {:class => "registration"}) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id='first-input'>
    <%= form.text_field :name, placeholder: "Name" %>
  </div>

  <div id="dropdown">
    <%= form.select :icon, Group::ICONS.invert, { include_blank: true }, { required: true } %>
  </div>

  <div>
    <%= form.submit "Add", class: 'submit' %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>", class='category-card'>
  <div class='icon'>
    <%= content_tag :i, "", class: "fa #{group.icon}" %>
  </div>
  <p><%= group.name %></p>
  <p class="total"><strong><%= number_to_currency(group.total_amount) %></strong></p>
</div>

app/views/groups/index.html.erb
<%= stylesheet_link_tag 'registration' %>
<main>
  <nav class="register">
    <h2>CATEGORIES</h2>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'sign-out' %>
  </nav>
  <p style="color: green"><%= notice %></p>

  <div id="groups", class="category-container">
    <% if @groups.empty? %>
      <p class="text-center"> <i> Category list is empty </i></p>
    <% else %>
      <% @groups.each do |group| %>
        <%= link_to group_expenses_path(group) do %>
          <%= render group %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <div class='button-outline'>
    <%= link_to "ADD A NEW CATEGORY", new_group_path, class: 'add-button' %>
  </div>
</main>

app/views/groups/new.html.erb
<%= stylesheet_link_tag 'registration' %>
<nav class="register">
  <%= link_to groups_path, class: 'arrow-link' do %>
    <i class="fa fa-solid fa-arrow-left"></i>
  <% end %>
  <h2>ADD CATEGORY</h2>
</nav>

<%= render "form", group: @group %>